[tool.poetry]
name = "features-service"
version = "0.1.0"
description = "Feature engineering service"

[tool.poetry.dependencies]
python = "^3.11"
pandas = "^2.1.4"
numpy = "^1.26.3"
sqlalchemy = "^2.0.25"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.4"
